[package]
name = "pulse"
version = "1.0.3"
description = "A quiet system layer for Windows, bringing media, notifications, and system activity into one compact surface."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "time"] }
base64 = "0.23.1"
windows = { version = "0.58.0", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_Foundation", "Win32_Graphics_Gdi", "Foundation"] }
winreg = "0.56.0"
tauri-plugin-global-shortcut = "2.4.0"
tauri-plugin-single-instance = "2.5.1"
tauri-plugin-autostart = "2.6.0"
axum = "0.8.9"

[target.'cfg(windows)'.dependencies.windows]
version = "0.58.0"
features = [
    "Foundation_Collections",
    "Media_Control",
    "Storage_Streams",
    "UI_Notifications",
    "UI_Notifications_Management",
    "Data_Xml_Dom",
    "Foundation",
    "ApplicationModel",
    "Win32_System_Com",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_Storage_Packaging_Appx",
    "Win32_Foundation",
    "Win32_System_Power",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
    "Win32_Devices_Bluetooth",
    "Win32_Devices_Usb",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_Security",
]


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
